#!/bin/bash
PKG=sekai
VER=0.4.0
git clone . $PKG-$VER
rm -rf $PKG-$VER/debian
cp -r debian $PKG-$VER/debian
rm -rf $PKG-$VER/.git
#rm $PKG-$VER/gitbuild
tar czvf $PKG'_'$VER.orig.tar.gz $PKG-$VER
cd $PKG-$VER
debuild -us -uc -S
cd ..
rm -rf $PKG-$VER

