mbrola: mbrola_dummy.cpp voicebank_meta.cpp voice_synth.cpp
	g++ -std=c++11 mbrola_dummy.cpp voicebank_meta.cpp voice_synth.cpp -o mbrola -lsekai -lworld -lfftw3 -lsndfile
#TODO check depends ,upgrade to cmake

